repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.38.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        exclude: versions

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.257
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: "mypy"
        additional_dependencies:
          [
            "pydantic",
            "fastapi",
            "pytest"
          ]
