version: '3'
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - .:/workspace
      - python-packages:/usr/local/lib/python3.11/site-packages
      - python-bin:/usr/local/bin
    depends_on:
      - db
    command: ["scripts/run-dev.sh"]

  db:
    restart: always
    image: postgres:12.1-alpine
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

volumes:
  python-packages:
  python-bin:
  db-volume: